### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by piyanatk** [UKZN-Astronomy/corrcal#1]
The README file should be converted to the markdown format and update with at least the following information:

- [ ] A few sentence describing what the code does
- [ ] Brief description of correlation calibration with a link to @sievers' paper
- [ ] Motivation specific to this repository, i.e. why we are updating @sievers' original repository
- [ ] Package details
- [ ] Installation, including dependencies
- [ ] Usage
- [ ] Community Guideline (i.e., how to contribute)
- [ ] Licensing
- [ ] Maintainers (i.e., contact information)

**Comment by ronniyjoseph** [comment]
A reference to Sievers 17' arxiv pre-print?
And something along the lines of the current example.

**Comment by ronniyjoseph** [comment]
Also a few comments from the original corrcal2_example code that should be in the README

#You'll need to compile corrcal2_funs.c into a shared library with e.g.
#gcc-4.9 -fopenmp -std=c99 -O3 -shared -fPIC -o libcorrcal2_funs.so corrcal2_funs.c -lm -lgomp   
#the library will need to be in your LD_LIBRARY_PATH.  If it doesn't show up
#and you compiled in the current directory, either do
#export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:.
#or change the ctypes.cdll.LoadLibrary call in corrcal2.py to have your full path location

**Comment by ronniyjoseph** [comment]
@piyanatk mentioned that the compiling line supplied in the example code only works with GNU's gcc.

> apple gcc is based on clang and doesn’t support -fopenmp tag
I think we just have to note this in the readme

**Comment by piyanatk** [comment]
@ronniyjoseph Now that we have a somewhat usable python package, can you start updating the README? It should be written in Markdown, and I suggest that we use [pyuvdata](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/README.md) as a guide (also check the first post). Feel free to commit, and we will discuss and further update it.

**Comment by piyanatk** [comment]
Done in 74451fb2.
