### ISSUE TITLE
Comparing Cholesky and BLAS/LAPACK decomposition

### ISSUE THREAD

**Issue by piyanatk** [UKZN-Astronomy/corrcal#14]
Originally posted by @ronniyjoseph in #5 (comment)

@sievers' arXiv pre-print discusses how c-code actually slows corrcal down for small problems:

> For small (∼ 100 antenna) problems with only a few source/redundant vectors, using BLAS/LAPACK actually slows down the code, since the function overhead for e.g. Cholesky decomposition of 2x2 blocks is non-negligible. So, the reference implementation fully self-contained.

@Mdlalose, @Zahra-Kader, @ronniyjoseph Have you run tests to confirm this? If not, we should put it in a to do list.

**Comment by ronniyjoseph** [comment]
@piyanatk I have not tested this myself, I've only run the code on the 144 antenna example supplied in the example. And a 36 hexagon, but I did not do speed comparisons

**Comment by piyanatk** [comment]
According to Jon, BLAS is not being used in the current C codes.

**Comment by Mdlalose** [comment]
I'll put it on do list.

**Comment by piyanatk** [comment]
Dropping this issue since blas has not been implemented in the current code.
