### ISSUE TITLE
Switch to CFFI

### ISSUE THREAD

**Issue by piyanatk** [UKZN-Astronomy/corrcal#18]
Following up from the discussion in #8 and what we learned from #10, it seems that switching from `ctypes` to `cffi` will improve the wrapper interface and streamline the code compilation. 

All C libraries loading and wrapping codes that are currently declared as global variables in `corrcal.py` can be placed in a`build_cffi.py` script in the root directory of the repository. Then, we can use the `cffi_modules` option with `setuptools` in `setup.py` to streamline the compiling and wrapping of the C cod. This seems to be what is being done in the [21cmFAST](https://github.com/21cmfast/21cmFAST) repository, I think.

 I will fork from the restructure branch to investigate this.

**Comment by piyanatk** [comment]
Since the `ctypes` implementation is working, @steven-murray suggested that we drop or postpone this issue and and instead focus on testing corrcal functions and developing Python branch. Agree, @ronniyjoseph ?

**Comment by ronniyjoseph** [comment]
For my personal benefit I agree, i.e. understanding the behaviour of corrcal. A pythonic version of corrcal is most likely the easiest way to get a feel for how corrcal works.

**Comment by piyanatk** [comment]
Dropping this issue with PR https://github.com/UKZN-Astronomy/corrcal/pull/21 merged to master.
