### ISSUE TITLE
Directory Restructure

### ISSUE THREAD

**Issue by piyanatk** [UKZN-Astronomy/corrcal#2]
The repository need to be restructured into a proper Python package. How we proceed will depend on #3.

**Comment by piyanatk** [comment]
I have created a new [branch](https://github.com/UKZN-Astronomy/corrcal/tree/restructure) for restructuring purpose.

**Comment by piyanatk** [comment]
Done in https://github.com/UKZN-Astronomy/corrcal/commit/9ad38205dbe59cee708ff7bc76b16263f00680f8

**Comment by piyanatk** [comment]
@ronniyjoseph Can you test if the restructure branch work? Since we have issue #11 , try it with the per-existing corrcal library.

**Comment by ronniyjoseph** [comment]
The newly structured branch works if I use a corrcal library that was compiled two months ago.
