### ISSUE TITLE
Put main package in src directory

### ISSUE THREAD

**Issue by steven-murray** [UKZN-Astronomy/corrcal#23]
The problem of it loading the local package rather than the installed one is a common problem and the most suggested fix is to put your actual package in a (non-python-package) `src/` folder. So you'd have:

```
corrcal/
    setup.py
    src/
        corrcal/
            __init__.py
```

This will also help in testing (because pytest will by default pick up the local package rather than the installed one, which is _usually_ not what you want!)

See https://blog.ionelmc.ro/2014/05/25/python-packaging/ for example.

**Comment by piyanatk** [comment]
PR submitted #30
