### ISSUE TITLE
Wrapper.py Imports of c library

### ISSUE THREAD

**Issue by ronniyjoseph** [UKZN-Astronomy/corrcal#32]
`LIB_LOC = glob(site.getsitepackages()[0] + "/corrcal*/corrcal/c_corrcal*.so")[0]`

After the moving of corrcal into src (#30), the path needs to be changed accordingly, I think?

**Comment by piyanatk** [comment]
@ronniyjoseph I cannot reproduce that issue. `c_corrcal*.so` should be installed at the root of the package directory `.../site-packages/corrcal/`. That was my intention. The package directory should also just say `corrcal`, so you should not need the wildcard there. See below.
```bash
(corrcal) piyanat at nezha in ~/src/corrcal on restructure*
$ ls /Users/piyanat/src/miniconda3/envs/corrcal/lib/python3.7/site-packages/corrcal
corrcal/                              corrcal-0.1.dev78+g404d32f.dist-info/ 
(corrcal) piyanat at nezha in ~/src/corrcal on restructure*
$ ls /Users/piyanat/src/miniconda3/envs/corrcal/lib/python3.7/site-packages/corrcal
__init__.py                     __pycache__                     c_corrcal.cpython-37m-darwin.so corrcal.py                      data                            src                             test                            wrapper.py
(corrcal) piyanat at nezha in ~/src/corrcal on restructure*
$ ls /Users/piyanat/src/miniconda3/envs/corrcal/lib/python3.7/site-packages/corrcal-0.1.dev78+g404d32f.dist-info/
INSTALLER     LICENSE.md    METADATA      RECORD        WHEEL         top_level.txt
```
Can you pull again to make sure that you have the latest commit, and do `pip uninstall -v corrcal` and `pip install -v .` and post the screen dump here?

**Comment by ronniyjoseph** [comment]
Did a git pull  from master just in case, but I am on the latest commit. Here are the outputs you asked for!

pip uinstall -v corrcal 

`
Uninstalling corrcal-0.1.dev81+gaa9b98b.d20200214:
  Would remove:
    /home/ronniyjoseph/Software/anaconda3/lib/python3.7/site-packages/corrcal-0.1.dev81+gaa9b98b.d20200214-py3.7-linux-x86_64.egg
  Will actually move:
    /home/ronniyjoseph/Software/anaconda3/lib/python3.7/site-packages/corrcal-0.1.dev81+gaa9b98b.d20200214-py3.7-linux-x86_64.egg
Proceed (y/n)? y
  Created temporary directory: /home/ronniyjoseph/Software/anaconda3/lib/python3.7/site-packages/~orrcal-0.1.dev81+gaa9b98b.d20200214-py3.7-linux-x86_64.egg
  Removing file or directory /home/ronniyjoseph/Software/anaconda3/lib/python3.7/site-packages/corrcal-0.1.dev81+gaa9b98b.d20200214-py3.7-linux-x86_64.egg
  Removing pth entries from /home/ronniyjoseph/Software/anaconda3/lib/python3.7/site-packages/easy-install.pth:
  Removing entry: ./corrcal-0.1.dev81+gaa9b98b.d20200214-py3.7-linux-x86_64.egg
  Successfully uninstalled corrcal-0.1.dev81+gaa9b98b.d20200214
`

**Comment by ronniyjoseph** [comment]
python setup.py install -v

`
running install
running bdist_egg
running egg_info
writing src/corrcal.egg-info/PKG-INFO
writing dependency_links to src/corrcal.egg-info/dependency_links.txt
writing requirements to src/corrcal.egg-info/requires.txt
writing top-level names to src/corrcal.egg-info/top_level.txt
writing manifest file 'src/corrcal.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/corrcal
copying build/lib.linux-x86_64-3.7/corrcal/__init__.py -> build/bdist.linux-x86_64/egg/corrcal
copying build/lib.linux-x86_64-3.7/corrcal/corrcal.py -> build/bdist.linux-x86_64/egg/corrcal
copying build/lib.linux-x86_64-3.7/corrcal/wrapper.py -> build/bdist.linux-x86_64/egg/corrcal
creating build/bdist.linux-x86_64/egg/corrcal/data
copying build/lib.linux-x86_64-3.7/corrcal/data/signal_sparse2_test.dat -> build/bdist.linux-x86_64/egg/corrcal/data
copying build/lib.linux-x86_64-3.7/corrcal/data/__init__.py -> build/bdist.linux-x86_64/egg/corrcal/data
copying build/lib.linux-x86_64-3.7/corrcal/data/ant1.dat -> build/bdist.linux-x86_64/egg/corrcal/data
copying build/lib.linux-x86_64-3.7/corrcal/data/ant2.dat -> build/bdist.linux-x86_64/egg/corrcal/data
copying build/lib.linux-x86_64-3.7/corrcal/data/gtmp.dat -> build/bdist.linux-x86_64/egg/corrcal/data
copying build/lib.linux-x86_64-3.7/corrcal/data/vis.dat -> build/bdist.linux-x86_64/egg/corrcal/data
creating build/bdist.linux-x86_64/egg/corrcal/src
copying build/lib.linux-x86_64-3.7/corrcal/src/corrcal_c_funcs.h -> build/bdist.linux-x86_64/egg/corrcal/src
copying build/lib.linux-x86_64-3.7/corrcal/src/corrcal_c_funcs.c -> build/bdist.linux-x86_64/egg/corrcal/src
copying build/lib.linux-x86_64-3.7/corrcal/c_corrcal.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/corrcal
creating build/bdist.linux-x86_64/egg/corrcal/test
copying build/lib.linux-x86_64-3.7/corrcal/test/__init__.py -> build/bdist.linux-x86_64/egg/corrcal/test
copying build/lib.linux-x86_64-3.7/corrcal/test/test_corrcal_fof.py -> build/bdist.linux-x86_64/egg/corrcal/test
copying build/lib.linux-x86_64-3.7/corrcal/test/corrcal_example.py -> build/bdist.linux-x86_64/egg/corrcal/test
copying build/lib.linux-x86_64-3.7/libcorrcal.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/corrcal/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/corrcal/corrcal.py to corrcal.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/corrcal/wrapper.py to wrapper.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/corrcal/data/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/corrcal/test/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/corrcal/test/test_corrcal_fof.py to test_corrcal_fof.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/corrcal/test/corrcal_example.py to corrcal_example.cpython-37.pyc
creating stub loader for corrcal/c_corrcal.cpython-37m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/corrcal/c_corrcal.py to c_corrcal.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying src/corrcal.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/corrcal.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/corrcal.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/corrcal.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/corrcal.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
corrcal.__pycache__.c_corrcal.cpython-37: module references __file__
corrcal.data.__pycache__.__init__.cpython-37: module references __path__
creating 'dist/corrcal-0.1.dev81+gaa9b98b.d20200214-py3.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing corrcal-0.1.dev81+gaa9b98b.d20200214-py3.7-linux-x86_64.egg
creating /home/ronniyjoseph/Software/anaconda3/lib/python3.7/site-packages/corrcal-0.1.dev81+gaa9b98b.d20200214-py3.7-linux-x86_64.egg
Extracting corrcal-0.1.dev81+gaa9b98b.d20200214-py3.7-linux-x86_64.egg to /home/ronniyjoseph/Software/anaconda3/lib/python3.7/site-packages
Adding corrcal 0.1.dev81+gaa9b98b.d20200214 to easy-install.pth file

Installed /home/ronniyjoseph/Software/anaconda3/lib/python3.7/site-packages/corrcal-0.1.dev81+gaa9b98b.d20200214-py3.7-linux-x86_64.egg
Processing dependencies for corrcal==0.1.dev81+gaa9b98b.d20200214
Searching for numpy==1.15.1
Best match: numpy 1.15.1
Adding numpy 1.15.1 to easy-install.pth file

Using /home/ronniyjoseph/Software/anaconda3/lib/python3.7/site-packages
Finished processing dependencies for corrcal==0.1.dev81+gaa9b98b.d20200214
`

**Comment by ronniyjoseph** [comment]
Wait your right! I was looking in the wrong folder. This issue should be closed

**Comment by piyanatk** [comment]
Aha. 
**Use**
`pip install .`

**Do not use**
`python setup.py install`

Read the README @ronniyjoseph. :)
