### ISSUE TITLE
Which C extension module should we use?

### ISSUE THREAD

**Issue by piyanatk** [UKZN-Astronomy/corrcal#8]
The current Python codes use both `ctypes`and `cffi` to interface with the C functions. These are two different C interfacing modules: `ctypes` is in the standard library, whereas `cffi` is a newer external module. I am not sure if they should be mixed as in the current codes, and `cffi` seems to be better(?) according to online discussion, so we may want to consider dropping `ctypes` for `cffi`. Another common option for working with C in Python is `Cython`, and there are many more (see [here](https://kos.gd/posts/5-ways-to-use-python-with-native-code/) and [here](http://stromberg.dnsalias.org/~strombrg/speeding-python/))

**Comment by piyanatk** [comment]
Upon inspecting the code, it looks like `cffi` was loaded but never used. Perhaps, @sievers was just looking into it?

**Comment by ronniyjoseph** [comment]
Sorry that was me! I was looking into CFFI as a modern alternative to interfacing with C, except I never got round to actually implementing it. I was planning on removing it.

**Comment by piyanatk** [comment]
I see! @ronniyjoseph , Is the current implementation with `ctypes` working?

**Comment by ronniyjoseph** [comment]
Yes, the current implementation with ctypes works. However, yes there might some merit to investigating alternate c-interfaces

**Comment by piyanatk** [comment]
I think for now we should stick with ctypes. Improving the C code should be postpone to our next milestone. I am going to close this for now. We will reopen it once revisited this issue.
