### ISSUE TITLE
Absolute import path of c-code

### ISSUE THREAD

**Issue by ronniyjoseph** [UKZN-Astronomy/corrcal#9]
I found the import of the c-source a bit annoying, especially when swithcing between machines. Surely, there must be a way to solve this directly referencing the src folder without hard coding a path.

https://github.com/UKZN-Astronomy/corrcal/blob/5c9bf9ceaa91a763ea02388c27399409b631a9cb/corrcal/corrcal.py#L16

I thought about this more, it means the compiled version of [libcorrcal_funs.c](corrcal/src/corrcal_funs.c) needs to be compiled within src always. (Unlike what is currently intended)

Anyway, I made a branch that assumes you always compile within src.

**Comment by piyanatk** [comment]
We need a setup script to automatically compile and install the C library in the package environment directory (see #10). Then, `mylib` can be pointed to the package library path, I think. I will check on this.

**Comment by piyanatk** [comment]
Resolve in #10.
